using System;
using System.Collections.Generic;

namespace NovatecEnergyWeb.Models
{
    public partial class NfeInfNotaFiscal
    {
        public int CodigoIntInfNotaFiscal { get; set; }
        public string BnfeNNf { get; set; }
        public decimal BnfeSerie { get; set; }
        public string DadosNfe { get; set; }
        public string AnfeCodigoBarras { get; set; }
        public string AnfeChaveAcesso { get; set; }
        public decimal? AnfeCDv { get; set; }
        public string AnfeCNf { get; set; }
        public string AnfeNrecibo { get; set; }
        public string AnfeNprotocolo { get; set; }
        public string AnfeDataHoraProtocolo { get; set; }
        public bool? AnfeEnviada { get; set; }
        public bool? AnfeEmProcessamento { get; set; }
        public bool? AnfeCancelada { get; set; }
        public string IdentificaçãoNfe { get; set; }
        public string BnfeCUf { get; set; }
        public int? BnfeNatOp { get; set; }
        public string BnfeDescNatOp { get; set; }
        public string BnfeIndPag { get; set; }
        public string BnfeMod { get; set; }
        public DateTime? BnfeDEmi { get; set; }
        public DateTime? BnfeDSaiEnt { get; set; }
        public DateTime? BnfeHSaiEnt { get; set; }
        public decimal? BnfeTpNf { get; set; }
        public string BnfeCMunFg { get; set; }
        public string BnfeTpImp { get; set; }
        public decimal? BnfeTpEmis { get; set; }
        public string BnfeTpAmb { get; set; }
        public string BnfeFinNfe { get; set; }
        public string BnfeProcEmi { get; set; }
        public string BnfeVerProc { get; set; }
        public DateTime? BnfeDhCont { get; set; }
        public string BnfeXJust { get; set; }
        public string BnfeRefNfe { get; set; }
        public string DadosEmitenteRemetente { get; set; }
        public string CnfeCnpj { get; set; }
        public string CnfeCpf { get; set; }
        public string CnfeXNome { get; set; }
        public string CnfeXFant { get; set; }
        public string CnfeXLgr { get; set; }
        public string CnfeNro { get; set; }
        public string CnfeXCpl { get; set; }
        public string CnfeXBairro { get; set; }
        public string CnfeCMun { get; set; }
        public string CnfeXMun { get; set; }
        public string CnfeUf { get; set; }
        public string CnfeCep { get; set; }
        public string CnfeCPais { get; set; }
        public string CnfeXPais { get; set; }
        public string CnfeFone { get; set; }
        public string CnfeIe { get; set; }
        public string CnfeIest { get; set; }
        public string CnfeIm { get; set; }
        public string CnfeCnae { get; set; }
        public string CnfeCrt { get; set; }
        public string DestinatarioCliente { get; set; }
        public string EnfeCnpj { get; set; }
        public string EnfeCpf { get; set; }
        public string EnfeXNome { get; set; }
        public string EnfeXFant { get; set; }
        public string EnfeXLgr { get; set; }
        public string EnfeNro { get; set; }
        public string EnfeXCpl { get; set; }
        public string EnfeXBairro { get; set; }
        public string EnfeCMun { get; set; }
        public string EnfeXMun { get; set; }
        public string EnfeUf { get; set; }
        public string EnfeCep { get; set; }
        public string EnfeCPais { get; set; }
        public string EnfeXPais { get; set; }
        public string EnfeFone { get; set; }
        public string EnfeIe { get; set; }
        public string EnfeIsuf { get; set; }
        public string EnfeEmail { get; set; }
        public string LocalRetirada { get; set; }
        public string FnfeCnpj { get; set; }
        public string FnfeCpf { get; set; }
        public string FnfeXLgr { get; set; }
        public string FnfeNro { get; set; }
        public string FnfeXCpl { get; set; }
        public string FnfeXBairro { get; set; }
        public string FnfeCMun { get; set; }
        public string FnfeXMun { get; set; }
        public string FnfeUf { get; set; }
        public string LocalEntrega { get; set; }
        public string GnfeCnpj { get; set; }
        public string GnfeCpf { get; set; }
        public string GnfeXLgr { get; set; }
        public string GnfeNro { get; set; }
        public string GnfeXCpl { get; set; }
        public string GnfeXBairro { get; set; }
        public string GnfeCMun { get; set; }
        public string GnfeXMun { get; set; }
        public string GnfeUf { get; set; }
        public string DadosTransporte { get; set; }
        public string XnfeModFrete { get; set; }
        public string XnfeCnpj { get; set; }
        public string XnfeCpf { get; set; }
        public string XnfeXNome { get; set; }
        public string XnfeIe { get; set; }
        public string XnfeXEnder { get; set; }
        public string XnfeXMun { get; set; }
        public string XnfeUf { get; set; }
        public decimal? XnfeVServ { get; set; }
        public decimal? XnfeVBcret { get; set; }
        public decimal? XnfePIcmsret { get; set; }
        public decimal? XnfeVIcmsret { get; set; }
        public string XnfeCfop { get; set; }
        public string XnfeCMunFg { get; set; }
        public string XnfePlacaVeic { get; set; }
        public string XnfeUfVeic { get; set; }
        public string XnfeRntcVeic { get; set; }
        public string XnfePlacaReboque { get; set; }
        public string XnfeUfReboque { get; set; }
        public string XnfeRntcReboque { get; set; }
        public string XnfeVagao { get; set; }
        public string XnfeBalsa { get; set; }
        public float? XnfeQVol { get; set; }
        public string XnfeEspecie { get; set; }
        public string XnfeMarca { get; set; }
        public decimal? XnfeNVol { get; set; }
        public decimal? XnfePesoL { get; set; }
        public decimal? XnfePesoB { get; set; }
        public string XnfeNLacre { get; set; }
        public string DadosCobrança { get; set; }
        public int? YnfeQtdadeDup { get; set; }
        public string YnfeNFat { get; set; }
        public double? YnfeVOrig { get; set; }
        public double? YnfeVDesc { get; set; }
        public double? YnfeVLiq { get; set; }
        public string YnfeNDup1 { get; set; }
        public DateTime? YnfeDVenc1 { get; set; }
        public double? YnfeVDup1 { get; set; }
        public string YnfeTodasDuplicatas { get; set; }
        public string InformaçõesAdicionais { get; set; }
        public string ZnfeIdAdicionaisIcms { get; set; }
        public string ZnfeIdAdicionaisIpi { get; set; }
        public string ZbnfeXNemp { get; set; }
        public string ZbnfeXPed { get; set; }
        public string ZbnfeContrato { get; set; }
        public string ValoresNfe { get; set; }
        public decimal? WnfeTotal { get; set; }
        public decimal? WnfeIcmstot { get; set; }
        public decimal? WnfeVBcicms { get; set; }
        public decimal? WnfeVIcms { get; set; }
        public decimal? WnfeVBcst { get; set; }
        public decimal? WnfeVSt { get; set; }
        public decimal? WnfeVProd { get; set; }
        public decimal? WnfeVFrete { get; set; }
        public decimal? WnfeVIpifrete { get; set; }
        public decimal? WnfeVSeg { get; set; }
        public decimal? WnfeVDesc { get; set; }
        public decimal? WnfeVIi { get; set; }
        public decimal? WnfeVIpi { get; set; }
        public decimal? WnfeVPis { get; set; }
        public decimal? WnfeVCofins { get; set; }
        public decimal? WnfeVOutras { get; set; }
        public decimal? WnfeVNf { get; set; }
        public decimal? WnfeIssqntot { get; set; }
        public decimal? WnfeVServ { get; set; }
        public decimal? WnfeVBciss { get; set; }
        public decimal? WnfeVIss { get; set; }
        public decimal? WnfeVPisServ { get; set; }
        public decimal? WnfeVCofinsServ { get; set; }
        public decimal? WnfeReTrib { get; set; }
        public decimal? WnfeVRetPis { get; set; }
        public decimal? WnfeVRetCofins { get; set; }
        public decimal? WnfeVRetCsll { get; set; }
        public decimal? WnfeVBcirrf { get; set; }
        public decimal? WnfeVIrrf { get; set; }
        public decimal? WnfeVBcretPrev { get; set; }
        public decimal? WnfeVRetPrev { get; set; }
        public int? IdmodEb { get; set; }
        public string _ { get; set; }
        public string ZnfeInfCpl { get; set; }
        public string ZnfeInfAdFisco { get; set; }
        public string ZnfeInfAdIpi { get; set; }
        public string ZnfeInfAdIcms { get; set; }
        public string CamposAdicionais { get; set; }
        public string InfoPagto { get; set; }
        public decimal? Processado { get; set; }
        public string LeiTransparência { get; set; }
        public decimal? VTotTrib { get; set; }
    }
}
